---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false

  tasks:

  - name: Install Mirror Quay
    include_role:
      name: install_quay
    vars:
      dest_registry: quay.example.opentlc.com
