---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false


  tasks:

  - name: mirroring-operator
    include_role:
      name: update-cluster
    vars:
      cluster_home: /root/aro
      registry_user: jinzha1@redhat.com
      dest_registry: quay03.example.opentlc.com
      soure_operator_index: redhat-operator-index
      new_operator_index: storage-operator-index
      mirror_home: /opt/registry/mirror-quay-operator
      ocp_version: v4.10
      dest_registry_port: 8443
      
