---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false

  tasks:

  - name: 01 install ansible collection
    ansible.builtin.shell: |
      ansible-galaxy collection install community.general
      ansible-galaxy collection install ansible.posix
      ansible-galaxy collection install containers.podman
      ansible-galaxy collection list
      export collections_paths=$(ansible-galaxy collection list | grep "^#" | sed -e "s/^#\s*//g")


